version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: apt_orders_db
    environment:
      POSTGRES_DB: apt_orders
      POSTGRES_USER: apt_user
      POSTGRES_PASSWORD: apt_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apt_user -d apt_orders"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
